# Import Libraries

In [1]:
import pandas as pd

# Read the CSV File

In [2]:
Coffee_df = pd.read_csv("https://raw.githubusercontent.com/DATA-606-SPRING-2023-TUE/nicholas_data606/main/data/coffee_df_with_type_and_region.csv")
Coffee_df = Coffee_df.drop(columns=['with_milk'])
Coffee_df.head()

,slug,all_text,rating,roaster,name,region_africa_arabia,region_caribbean,region_central_america,region_hawaii,region_asia_pacific,...,review_date,agtron,aroma,acid,body,flavor,aftertaste,desc_1,desc_2,desc_3
0,https://www.coffeereview.com/review/wilton-ben...,\n\n\n95\n\n\nJBC Coffee Roasters\nWilton Ben...,95,JBC Coffee Roasters,Wilton Benitez Geisha,0,0,0,0,0,...,November 2022,59/81,9.0,9.0,9.0,9.0,9.0,"Richly floral-toned, exceptionally sweet. Dist...",Produced by Wilton Benitez of Macarena Farm en...,"A nuanced, complex experimentally processed Co..."
1,https://www.coffeereview.com/review/colombia-c...,\n\n\n95\n\n\nBird Rock Coffee Roasters\nColo...,95,Bird Rock Coffee Roasters,Colombia Cerro Azul Geisha,0,0,0,0,0,...,November 2022,62/80,9.0,9.0,9.0,9.0,9.0,"Richly aromatic, chocolaty, fruit-toned. Dark ...",Produced by Rigoberto Herrera of Granja La Esp...,"A trifecta of fruit, chocolate and flowers, bo..."
2,https://www.coffeereview.com/review/yirgacheff...,\n\n\n94\n\n\nRegent Coffee\nYirgacheffe Meng...,94,Regent Coffee,Yirgacheffe Mengesha Natural,1,0,0,0,0,...,November 2022,60/77,9.0,9.0,9.0,9.0,8.0,"High-toned, fruit-driven. Boysenberry, pear, c...",Produced at Mengesha Farm from selections of i...,A fruit medley in a cup — think boysenberry an...
3,https://www.coffeereview.com/review/colombia-t...,\n\n\n93\n\n\nRegent Coffee\nColombia Tolima ...,93,Regent Coffee,Colombia Tolima Finca El Mirador Washed Anaerobic,0,0,0,0,0,...,November 2022,59/79,9.0,9.0,8.0,9.0,8.0,"Delicately fruit-toned. Guava, ginger blossom,...",Produced by Victor Gutiérrez of Finca Mirador ...,"An appealing washed anaerobic cup: deep-toned,..."
4,https://www.coffeereview.com/review/panama-gei...,\n\n\n94\n\n\nTheory Coffee Roasters\nPanama ...,94,Theory Coffee Roasters,Panama Geisha Finca Debra Symbiosis,0,0,1,0,0,...,November 2022,62/80,9.0,9.0,9.0,9.0,8.0,"Richly fruit-forward, floral-toned. Lychee, te...",Produced by Jamison Savage of Finca Debra enti...,A floral- and fruit-driven anaerobic natural P...

In [3]:
Coffee_df.shape

(2282, 36)

In [4]:
Coffee_df.columns

Index(['slug', 'all_text', 'rating', 'roaster', 'name', 'region_africa_arabia',
       'region_caribbean', 'region_central_america', 'region_hawaii',
       'region_asia_pacific', 'region_south_america', 'type_espresso',
       'type_organic', 'type_fair_trade', 'type_decaffeinated',
       'type_best_value', 'type_pod_capsule', 'type_blend', 'type_estate',
       'type_peaberry', 'type_barrel_aged', 'type_aged', 'location', 'origin',
       'roast', 'est_price', 'review_date', 'agtron', 'aroma', 'acid', 'body',
       'flavor', 'aftertaste', 'desc_1', 'desc_2', 'desc_3'],
      dtype='object')

# DATA CONVERSIONS

# Combine the region columns into one column

In [5]:
print(Coffee_df.shape)
print(Coffee_df.region_africa_arabia.value_counts()[1]
      + Coffee_df.region_caribbean.value_counts()[1]
      + Coffee_df.region_central_america.value_counts()[1]
      + Coffee_df.region_hawaii.value_counts()[1]
      + Coffee_df.region_asia_pacific.value_counts()[1]
      + Coffee_df.region_south_america.value_counts()[1])

print(Coffee_df.region_africa_arabia.value_counts()[1])
print(Coffee_df.region_caribbean.value_counts()[1])
print(Coffee_df.region_central_america.value_counts()[1])
print(Coffee_df.region_hawaii.value_counts()[1])
print(Coffee_df.region_asia_pacific.value_counts()[1])
print(Coffee_df.region_south_america.value_counts()[1])

def categorize_region(row):
  if row['region_africa_arabia'] == 1:
    return 'africa_arabia'
  if row['region_caribbean'] == 1:
    return 'caribbean'
  if row['region_central_america'] == 1:
    return 'central_america'
  if row['region_hawaii'] == 1:
    return 'hawaii'
  if row['region_asia_pacific'] == 1:
    return 'asia_pacific'
  if row['region_south_america'] == 1:
    return 'south_america'
  return 'other'

Coffee_df['region'] = Coffee_df.apply(lambda row: categorize_region(row), axis=1)

print(Coffee_df.region.value_counts()['africa_arabia'])
print(Coffee_df.region.value_counts()['caribbean'])
print(Coffee_df.region.value_counts()['central_america'])
print(Coffee_df.region.value_counts()['hawaii'])
print(Coffee_df.region.value_counts()['asia_pacific'])
print(Coffee_df.region.value_counts()['south_america'])
print(Coffee_df.region.value_counts()['other'])

Coffee_df['region']

(2282, 36)
1990
889
11
479
128
112
371
889
11
472
125
100
359
326

0         south_america
1         south_america
2         africa_arabia
3         south_america
4       central_america
             ...
2277    central_america
2278      africa_arabia
2279    central_america
2280    central_america
2281    central_america
Name: region, Length: 2282, dtype: object

# Convert review_date Strings to datetime

This allows the reviews to be sorted by date

In [6]:
Coffee_df.review_date.unique

<bound method Series.unique of 0       November 2022
1       November 2022
2       November 2022
3       November 2022
4       November 2022
            ...
2277    December 2017
2278    December 2017
2279    December 2017
2280    December 2017
2281    December 2017
Name: review_date, Length: 2282, dtype: object>

In [7]:
Coffee_df['review_date'] = pd.to_datetime(Coffee_df['review_date'], format='%B %Y')
Coffee_df['review_date']

0      2022-11-01
1      2022-11-01
2      2022-11-01
3      2022-11-01
4      2022-11-01
          ...
2277   2017-12-01
2278   2017-12-01
2279   2017-12-01
2280   2017-12-01
2281   2017-12-01
Name: review_date, Length: 2282, dtype: datetime64[ns]

# Convert est_price (object type) to a numeric value

In [8]:
Coffee_df.est_price.unique()

array(['$25.00/8 ounces', '$59.00/8 ounces', '$20.50/12 ounces',
       '$45.00/4 ounces', '$40.00/200 grams', '$43.00/200 grams',
       '$25.00/12 ounces', '$20.00/6 ounces', '$40.00/12 ounces',
       '$17.95/12 ounces', '$28.00/12 ounces', '$20.00/12 ounces',
       '$22.00/12 ounces', '$23.50/12 ounces', '$40.00/10 ounces',
       '$24.00/12 ounces', '$35.00/10 ounces', '$24.00/8 ounces',
       '$24.50/12 ounces', '$23.00/12 ounces', '$18.99/8 ounces',
       '$22.50/12 ounces', '$20.95/12 ounces', '$16.95/12 ounces',
       '$35.00/200 grams', '$19.25/12 ounces', 'NT $375/8 ounces',
       '$19.00/175 grams', 'NT $340/8 ounces', 'NT $900/4 ounces',
       'NT $400/8 ounces', 'NT $459/8 ounces', 'NT $350/8 ounces',
       '$19.00/12 ounces', 'NT $399/8 ounces', 'NT $249/8 ounces',
       'NT $429/8 ounces', '$21.60/12 ounces', 'NT $1,500/250 grams',
       '$21.00/12 ounces', '$22.00/6 ounces', '$25.00/250 grams',
       '$25.99/10 ounces', 'NT $550/200 grams', 'NT $380/200 grams',
       '$16.00/150 grams', '$45.00/12 ounces', '$23.00/10 ounces',
       '$26.00/12 ounces', 'NT $550/250 grams', '$16.00/12 ounces',
       '$10.00/12 ounces', '$13.00/12 ounces', '$16.50/12 ounces',
       '$5.00/12 ounces', '$5/12 ounces', '$17.00/12 ounces',
       '$10.00/16 ounces', '$10.00/4 ounces', '$10.00 / 8 ounces',
       'NT$500/4 ounces', '$45.99/12 ounces', '$18.95/12 ounces',
       'NT $800/20 grams', '$30.00/ 12 ounces', 'NT $460/8 ounces',
       'NT $550/454 grams', 'NT $550/227 grams', 'NT $500/227 grams',
       'NT$587/8 ounces', 'NT$275/8 ounces', 'NT$840/225g', 'NT$600/200g',
       '$NT$1000/200g', '$NT$520/200g', 'NT$650/230g', 'NT$399/8 ounces',
       'NT$700/8 ounces', '$18.00/12 ounces', '$17.50/12 ounces',
       '$30.00/12 ounces', 'NT $1200/4 ounces', 'NT $600/50 grams',
       'NT $325/8 ounces', 'NT $200/8 ounces', '$14.00/250 grams',
       '$13.00/250 grams', 'NT $450/200 grams', 'NT $500/200 grams',
       '$12.50/100 grams', 'CAD $30.00/250 grams', 'NT $520/227 grams',
       '$8.40/4 ounces', '$18.05/12 ounces', 'NT $680/230 grams',
       '$15.00/8 ounces', '$21.95/12 ounces', '$47.95/8 ounces',
       '$27.00/14 ounces', 'NT $2300/230 grams', '$19.50/10 ounces',
       '$30.00/4 ounces', 'NT $750/230 grams', 'NT $450/8 ounces',
       'NT $500/8 ounces', '$29.00/4 ounces', '$49.00/10 ounces',
       'NT $390/8 ounces', '$25.50/12 ounces', 'NT $300/4 ounces',
       'NT $350/4 ounces', 'NT $240/8 ounces', '$32.25/8 ounces',
       '$16.95/16 ounces', 'NT $850/240 grams', '$25.00/14 ounces',
       '$16.70/12 ounces', '$39.50/12 ounces', '$80.00/8 ounces',
       '$17.99/12 ounces', '$16.99/12 ounces', '$23.00/8 ounces',
       '$26.00/10 ounces', 'NT $888/225 grams', 'NT $275/200 grams',
       'NT $165/8 ounces', 'NT $600/227 grams', '$54.95/8 ounces',
       '$28.50/12 ounces', '$18.50/12 ounces', '$19.95/12 ounces',
       '$12.00/12 ounces', 'NT $400/16 ounces', 'NT $650/225 grams',
       '$15.00/12 ounces', '$21.50/16 ounces', '$18.50/16 ounces',
       '$8.00/4 ounces', '$50.00/4 ounces', '$18.00/8 ounces',
       '$60.00/150 grams', '$14.00/230 grams', '$18.99/16 ounces',
       'NT $1250/60 grams', 'NT $880/200 grams', 'NT $630/200 grams',
       'NT $420/200 grams', 'NT $550/4 ounces', '$19.00/6 ounces',
       'NT $450/227 grams', '$18.65/12 ounces', '$65.00/8 ounces',
       '$15.95/12 ounces', '$39.45/12 ounces', 'RM 130/350 grams',
       'RM 120/350 grams', 'NT $1800/60 grams', '£50/10 capsules',
       'NT $600/200 grams', 'NT $460/454 grams', '$18.99/12 ounces',
       '$18.75/12 ounces', '$19.50/12 ounces', '$24.50/5.5 ounces',
       'NT $349/8 ounces', '$26.50/6 ounces', 'NT $789/8 ounces',
       '$14.00/12 ounces', '$19.50/6 ounces', '$13.99/12 ounces',
       'NT $650/8 ounces', '$17.75/12 ounces', 'NT $500/100 grams',
       'NT $275/8 ounces', 'NT $800/8 ounces', '$18.45/12 ounces',
       'NT $360/8 ounces', '$62.95/8 ounces', '$22.50/10 ounces',
       '$27.50/12 ounces', '$25.00/6 ounces', 'NT $330/113 grams',
       '$19.99/12 ounces', 'HKD $498/105 grams', 'NT $620/100 grams',
       'NT $450/220 grams', '$33.00/200 grams', '$22.00/16 ounces',
       '$35.00/8 ounces', 'NT $600/8 ounces', 'NT $280/8 ounces',
       'NT $200/115 grams', '$16.00/5 ounces', 'NT $950/227 grams',
       '$25.00/4 ounces', '$35.00/12 ounces', '$16.00/4 ounces',
       'NT $350/227 grams', 'NT $400/ 227 grams', 'NT $700/4 ounces',
       'NT $400/4 ounces', '$17.99/ 12 ounces', '$17.00/4 ounces',
       '$140.00/4 ounces', 'NT $800/100 grams', 'NT $700/100 grams',
       '$65.95/8 ounces', 'NT $3600/100 grams', '$19.95/7 ounces',
       '$14.50/12 ounces', '$15.00/300 grams', 'NT $600/275 grams',
       '$17.95/16 ounces', '$13.25/12 ounces', '$12.99/12 ounces',
       '$18.20/24 ounces', '$9.98/12 ounces', '$17.50/10 ounces',
       'NT $400/225 grams', 'NT $160/454 grams', 'NT $160/227 grams',
       '$48.00/12 ounces', 'NT $350/ 8 ounces', 'NT $295/115 grams',
       'NT $750/227 grams', 'NT $250/200 grams', 'NT $350/200 grams',
       '$69.00/6 ounces', '$40.00/4 ounces', '$40.95/4 ounces',
       '$18.00/6 ounces', '$42.00/4 ounces', '$26.00/8 ounces',
       '$20.00/4 ounces', '$15.99/12 ounces', '$36.00/8 ounces',
       'NT $470/225 grams', 'NT $370/225 grams', 'NT $380/8 ounces',
       'NT $250/8 ounces', 'NT $300/8 ounces', '$49.95/8 ounces',
       '$24.99/12 ounces', 'NT $350/240 grams', 'NT $400/240 grams',
       'NT$400/227 grams', 'NT$350/227 grams', 'NT $500/227g',
       '$11.75/10.5 ounces', 'NT $1000/227 grams', 'NT $800/227 grams',
       'NT $490/150 grams', 'NT $480/400 grams', '$45.00/16 ounces',
       '$35.00/16 ounces', 'NT $300/200 grams', '$34.95/8 ounces',
       '$24.95/8 ounces', 'NT $450/240 grams', 'NT $210/8 ounces',
       '$38.50/12 ounces', 'NT $475/113 grams', '$13.95/4 ounces',
       '$29.00/12 ounces', 'NT $650/200 grams', 'NT $650/455 grams',
       'NT $350/230 grams', 'NT $300/230 grams',
       'NA (available in store only)', '$12.25/10.5 ounces',
       'NT $850/8 ounces', '$30.00/8 ounces', '$20.00/8 ounces',
       'NT $800/16 ounces', 'HKD $208/120 grams', 'NT$450/8 ounces',
       '£100/150-gram packet', '$16.00/10 ounces', '$12.00/8 ounces',
       'NT $550/8 ounces', '$50.00/6 ounces', '$19.00/4 ounces',
       '$21.99/12 ounces', '$20.99/12 ounces', '$75.00/12 ounces',
       'NT $1250/4 ounces', 'NT $1,400/4 ounces', 'NT $1,000/4 ounces',
       nan, '$280.00/70 grams; $200.00/50 grams', '$16.00/250 grams',
       '$16.50/250 grams', '$89.95/8 ounces', '$35.00/300 grams',
       'NT $575/4 ounces', 'NT $380/227 grams', '$150.00/4 ounces',
       '$145.00/4 ounces', '$26.50/4 ounces', '¥1680/100 grams',
       '$95.00/4 ounces', 'NT $375/4 ounces', '$60.00/8 ounces',
       '$120.00/6 ounces', 'NT $1000/200 grams', '$49.99/16 ounces',
       '$28.00/225 grams', '$11.99/4 ounces', '¥88/16 ounces',
       '¥78/16 ounces', 'NT $400/120 grams', 'NT $600/4 ounces',
       'NT $225/8 ounces', '$22.49/12 ounces', '$19.49/12 ounces',
       '$42.00/12 ounces', '$24.95/12 ounces', 'NT $250/227 grams',
       'NT $400/227 grams', 'NT $450/115 grams', '$14.99/12 ounces',
       '$13.95/12 ounces', 'NT $200/453 grams', 'NT $500/4 ounces',
       '$32.00/4 ounces', '$29.99/5 ounces', '$40.00/8 ounces',
       '$32.00/6 ounces', '£25.00/8 18-gram pouches', 'NT $760/4 ounces',
       'NT $280/10 capsules', 'NT $300/225 grams', '$24.95/4 ounces',
       '$21.50/8 ounces', '$27.00/12 ounces', '$13.01/12.64 ounces',
       '$80.00/12 ounces', 'NT $260/200 grams', '$10.99/10.5 ounces',
       '$14.95/12 ounces', 'NT $1780/250 grams', 'NT $570/250 grams',
       'NT $1580/250 grams', 'NT $600/100 grams', 'NT $1200/225 grams',
       'NT $260/8 ounces', 'NT $650/227 grams', '$30.00/6 ounces',
       'HKD $300/100 grams', 'HKD $138/100 grams', '$21.00/113 grams',
       '$45.00/175 grams', '$14.95/6 ounces', 'NT $755/113 grams',
       'NT $320/8 ounces', 'NT $400/230 grams', 'NT $260/227 grams',
       '$54.95/12 ounces', '$39.95/12 ounces', '$21.50/12 ounces',
       'NT $450/225 grams', 'NT $530/12 ounces', '$13.20/12 ounces',
       '$74.95/4 ounces', 'NT $410/8 ounces', 'NT $630/225 grams',
       'NT $290/8 ounces', 'NT $680/227 grams', 'HKD $118/200 grams',
       '¥2980/100 grams', 'NT $380/12 ounces', 'NT $200/160-ml bottle',
       '$5.50/12-ounce bottle', '$2.00/200-ml bottle',
       '$35.00/six 8-ounce cans', '$4.49/280 ml can',
       '$4.00/12-ounce bottle', '$14.00/four 8-ounce cans',
       '$4.25/12-ounce bottle', '$25.00/six 12-ounce cans',
       '$33.00/twelve 6-ounce cans', '$16.00/8 ounces',
       '$87.00/12 ounces', 'NT $500/150 grams', 'NT $650/150 grams',
       'NT $1450/150 grams', 'NT $350/250 grams', '$28.99/12 ounces',
       '$17.90/12 ounces', '$29.95/4 ounces', 'NT $350/16 ounces',
       '$17.99/16 ounces', '¥1,050/100 grams', 'NT $220/8 ounces',
       '$15.99/10 ounces', '$20.49/12 ounces', '$30.00/300 grams',
       '$15.80/12 ounces', '$24.75/12 ounces', 'NT $900/227 grams',
       'NT $320/200 grams', '$30.00/150-gram tin', 'NT $560/227 grams',
       '$32.99/16 ounces', 'NT $2200/16 ounces', '$14.74/16 ounces',
       '500 pesos/200 grams', 'NT $500/225 grams', 'NT $330/227 grams',
       '$10.00/8 ounces', '$11.00/375 ml. flask', '¥1280/100 grams',
       'NT $600/225 grams', 'NT $360/225 grams', 'NT $350/225 grams',
       '$28.00/8 ounces', '$49.95/7 ounces', '$17.50/8 ounces',
       '$12.99/11 ounces', '$16.20/12 ounces', '$29.95/12 ounces',
       '$14.99/seven single-serve pouches', '$87.50/8 ounces',
       '$120.00/16 ounces', '$33.00/8 ounces', '$50.00/7 ounces',
       '$47.00/12 ounces', '$12.50/12 ounces', 'NT $400/220 grams',
       'CAD $18.00/12 ounces', 'CAD $21.00/12 ounces', '$19.75/12 ounces',
       '$19.95/6 ounces', '$9.99/4 ounces', '$16.00/230 grams',
       'NT $270/8 ounces', '$14.20/12.64 ounces', '$15.75/12 ounces',
       '$39.95/4 ounces', '$19.95/4 ounces', '$28.80/500 grams',
       '$27.00/8 ounces', '$12.99/10 ounces', '¥ 1,580/100 grams',
       '¥ 2,640/50 grams', '$14.00/225 grams', '$29.50/12 ounces',
       'NT $372/227 grams', 'NT $252/227 grams', 'CAD $50/200 grams',
       'CAD $45/250 grams', '$22.95/12 ounces', 'NT $450/454 grams',
       '$16.95/6 ounces', 'NT $310/8 ounces', 'NT $620/8 ounces',
       '$18.95/16 ounces', 'NT $600/230 grams', '$18.65/8 ounces',
       'NT $1300/4 ounces', '$25.00/150 grams', '$39.00/12 ounces',
       'NT $599/227 grams', 'NT $499/227 grams', '$33.00/10 ounces',
       '$27.00/10 ounces', 'NT $450/460 grams', 'NT $1500/230 grams',
       'NT $520/200 grams', 'NT $900/100 grams', 'NT $1,000/200 grams',
       'NT $620/4 ounces', '¥ 2,420/200 grams', '$10.00/250 grams',
       'NT $470/227 grams', 'NT $360/115 grams', '$50.00/10 ounces',
       '$56.00/8 ounces', 'USD $206.00/8 ounces', 'NT $1100/8 ounces',
       '$55.00/8 ounces', 'NT $1,000/8 ounces', 'NT $300/100 grams',
       '$24.00/16 ounces', '$75.00/16 ounces', '$65.00/16 ounces',
       '$32.00/7 ounces', 'NT $350/20 grams', '$85.00/6 ounces',
       'NT $330/200 grams', '$74.95/8 ounces', '$39.95/8 ounces',
       '$20/12 ounces', 'NT $900/8 ounces', '£45/10 capsules',
       'NT $5,000/20 grams', '$64.95/4 ounces', '$29.00/8 ounces',
       '$31.00/8 ounces', 'NT $750/4 ounces', '$29.99/10 ounces',
       '$13.00/10 ounces', 'US $20.00/12 ounces', '$32.00/8 ounces',
       'NT $380/115 grams', 'NT $550/225 grams', 'CAD $22.00/225 grams',
       '$19.99 CAD/12 ounces', 'HK $80/200 grams', '$19.99/8 ounces',
       'NT $550/230 grams', 'NT $2500/100 grams', '$12.95/6 ounces',
       '$15.00/4 ounces', '$60.00/30 ounces', 'NT $500/16 ounces',
       '$18.25/12 ounces', '$22.99/12 ounces', 'NT $330/16 ounces',
       'NT $700/230 grams', '$20.00/16 ounces', '$24.99/10 ounces',
       '$18.49/12 ounces', '$16.99/14 ounces', '$50.00/12 ounces',
       'NT $550/450 grams', '$19.00/7 ounces', '$23.00/6 ounces',
       '$19.98/4 ounces', 'NT $520/250 grams', '$19.95/2 ounces',
       'NT $475/250 grams', 'NT $400/222 grams', 'NT $700/8 ounces',
       '$17.00/150 grams', '$11.50/12 ounces', '$3.99/8-ounce can',
       '$4.00/can', '$4.50/12 ounces', '$18.99/50 ounces',
       '$20.00/Four 12-ounce bottles',
       '$4.00/12-ounce bottle; $20.00/6-pack', '$4.59/10.5-ounce bottle',
       '$13.99/Four 8.4-ounce cans', 'NT $200/150 ml. bottle',
       '$46.50/12 9.5-ounce cans',
       '$18.00/4-12-ounce bottles; 32 ounces/$12; 64-ounces/$20.00',
       '$3.00/sachet (plus one donated)', '$15.00/20 ounces (2 types)',
       'NT $300/220 grams', '$38.00/8 ounces', '$13.50/12 ounces',
       '$18.95/4 ounces', '£50.00/10 capsules', '$30.00/10 ounces',
       '$35.00/7 ounces', '$17.80/12 ounces', 'NT $580/200 grams',
       'NT $225/4 ounces', '$36.00/12 ounces',
       '$45.95/8 ounces (currently on sale for $36.76)',
       '$34.95/6 ounces', '$15.00/12 ounces; $35.00/2 pounds',
       '$13.99/12 ounces ($79.00/5 pounds)', '$49.95/4 ounces',
       '$33.00/12 ounces', '$15.25/12 ounces', 'NT $530/200 grams',
       '$12.36/12 ounces', '$16.25/12 ounces', '$18.20/12 ounces',
       '$21.00/12 ounces (includes shipping)',
       '$16.00/12 ounces; $50.00/5 pounds', '$18.00/16 ounces',
       'HK $150/250 grams', '$19.99/340 grams', '$12.95/16 ounces',
       '$50.00/ 7 ounces', '$34.95/7 ounces', '$17.88/227 grams',
       '$16.88/227 grams', '€29.95/1 kilo (35.3 ounces)',
       '$18.40/12 ounces', '$10.95/12 ounces', '$14.99/10 ounces',
       '$11.29/12 ounces', '$6.99/16 ounces', '$4.99/12 ounces',
       '$9.29/22 ounces', '$8.99/32 ounces', '$10.49/12 ounces',
       'NT $1600/4 ounces', 'NT $320/227 grams', 'NT $440/8 ounces',
       '$19.95/8 ounces', '$14.25/12 ounces', '$16.00/14 ounces',
       '$35,000 LAK/250 grams', 'NT $1,000/100 grams', '$12.00/500 grams',
       'IDR $120,000/200 grams', '$15.00/500 grams', '$16.80/12 ounces',
       '$8.00/100 grams', 'NT $200/227 grams', 'CAD $18.00/300 grams',
       '$15.25/8 ounces', 'NT $570/200 grams', 'NT $450/250 grams',
       '$69.95/6 ounces', 'NT$300/8 ounces', '$100/18 grams',
       '$60.00/100 grams', 'NT $200/200 grams', 'NT $280/454 grams',
       '$17.20/12 ounces', '$19.20/12 ounces', '$16.90/12 ounces',
       'NT $1,400/8 ounces', 'NT $1,300/8 ounces', 'NT $1,100/8 ounces',
       '$125.00/4 ounces; limited availability', 'NT $700/16 ounces',
       'NT $680/225 grams', '$15.00/10 ounces', 'NT $500/230 grams',
       'NT $1200/200 grams', '$23.95/12 ounces', '$100.00/21 grams',
       '$39.95/8 ounces (packaged as a "duo" with Bourbon Rey Guatemala)',
       '$39.95/8 ounces (packaged as a "duo" with the Bourbon Rey Jamaica)',
       'AUD $18.00/18 grams', '$13.50/8 ounces', '$15.00/250 grams',
       'NT $380/454 grams', '$39.95/8 ounces*', 'NT $1200/16 ounces',
       '$16.25/10 ounces', 'See website for more information',
       '$54.95/6 ounces', 'NT $1350/230 grams', 'NT $1200/100 grams',
       '$50.00/8 ounces', 'AED $103.95/250 grams', 'AED $99.75/250 grams',
       'NT $600/450 grams', 'NT $380/450 grams', '$17.10/12 ounces',
       'NTD $300/200 grams', '$18.70/12 ounces', '$15.45/12 ounces',
       '$19.65/8 ounces', '$34.99/16 ounces', 'NT $1200/230 grams',
       '£40.50/10 capsules', 'NT $700/227 grams', '$25.75/4 ounces',
       '$60.00/10 ounces', '$NT 700/227 grams', 'NT $200/250 grams',
       '$18.95/8 ounces', '$206.00/8 ounces', '$16.40/12 ounces',
       '$13.34/4 ounces', '$15.50/12 ounces', '$21.20/12 ounces',
       'NT $700/400 grams', '$15.90/12 ounces', '9.9 Euros/225 grams',
       '$17.25/12 ounces', '$12.95/12 ounces', '$13.56/12 ounces',
       '$9.99/12 sticks', '18.00/12 ounces', 'NT $660/225 grams',
       'HK $125.00/250 grams', 'NT $180/8 ounces', '$49.50/4 ounces',
       '$31.00/10 ounces', '$29.00/10 ounces', '$63.95/8 ounces',
       '$49.00/8 ounces', '$19.00/200 grams', '$17.99/3 pounds',
       '$18.99/2 pounds', '$37.99/6 pounds', 'NTD $1200/225 grams',
       'NTD $600/225 grams', '$27.00/16 ounces', 'NT $490/16 ounces',
       '$7.12/120 grams', '$37.50/8 ounces', 'CAD $18.00/340 grams',
       '$19.00/8 ounces', 'NT $480/8 ounces', 'NT $650/16 ounces',
       'NT $360/16 ounces', '$48.95/8 ounces', '$36.95/8 ounces',
       '$28.00/500 grams', '$28.99/16 ounces', '$29.00/150 grams',
       'NT $850/225 grams', '$28.85/8 ounces', '$100/200 grams',
       'NT $250/225 grams', '$26.00/five 5-gram single-serve packets',
       '$19.99/16 ounces', '$44.95/8 ounces', 'CAD $29.99/32 ounces',
       'NT $250/16 ounces', '$55.00/12 ounces', '$30.00/250 grams',
       '$24.00/6 ounces', '$45.00/8 ounces', '$54.00/12 ounces',
       '$39.99/12 ounces', '$9.00/8 ounces',
       '$10.99/8 single-serve packets', '#23.00/12 ounces',
       'NT $300/227 grams', '$70.00/8 ounces', 'NT $1450/8 ounces',
       'CAD $15.00/200 grams', '$37.00/120 grams', '$13.50/10 ounces',
       '$12.25/12 ounces', 'NT $2600/227 grams', '$6.00/250 grams',
       '$75.00/8 ounces', '$14.45/12 ounces', '$16.75/12 ounces',
       '$11.95/12 ounces', 'NT $1400/16 ounces', 'NT $1500/16 ounces',
       'NT $2000/16 ounces', '$13.75/12 ounces', '$14.75/12 ounces',
       '$15.16/500 grams', '$22.15/500 grams',
       '$6.99/eight 3.3 gram packets',
       '$17.98/thirty 1.6-gram single-serve packets',
       '$16.00/five 5-gram single-serve packets',
       '$8.99/8 ounces (226 grams)', '$9.99/7 ounces (198 grams)',
       '$19.00/six 5-gram packets',
       '$15.00/six 5-gram single-serve packets',
       '$22.00/eight 5-gram tubes',
       '$16.98/45 grams (approx. 9 servings)', 'NT $550/16 ounces',
       'NT $580/8 ounces', 'NT $400/225 gram', 'KRW $14,000/200 grams',
       '$4.65/8.4-ounce can', '$20.00/250 grams', 'NT $600/16 ounces',
       'NT $520/16 ounces', 'NT $1500/8 ounces', 'NT $850/16 ounces',
       'NT 400/227 grams', 'CAD $15.00/250 grams',
       '$12.00/25.4-ounce bottle (seasonal)', '$3.49/11-ounce can',
       '$3.99/12-ounce can',
       '$65.99/12 10.5-ounce bottles (shipping within California only)',
       '$4.00/10-ounce bottle', '$4.50/12-ounce bottle',
       '$36.00/12 9.5-ounce cans', '$84.00/24 12-ounces bottles',
       '$5.00/12-ounce can', '$16.99/16 ounces', '$19.98/16 ounces',
       'CAD $16.00/16 ounces', '$15.99/16 ounces', '$20.50/16 ounces',
       'CAD $17.00/12 ounces',
       '$19.50/12 ounces online; $12.99/ounces in stores',
       'NT $750/16 ounces', 'NT $480/16 ounces', '$17.60/12 ounces',
       'NT $480/225 grams', 'NT $630/227 grams', 'NT $420/227 grams',
       'NT $450/16 ounces', 'CAD $29.00/200 grams', 'THB $320/250 grams',
       '$16.49/12 ounces', '$145.00/8 ounces', '$12.60/12 ounces',
       '$45.95/8 ounces', '$13.95/8 ounces', '$30.50/4 ounces',
       '$51.00/8 ounces', 'NT $950/8 ounces', '$9.94/4 ounces',
       'CAD $15.50/340 grams', 'NT $415/12 ounces',
       'KRW $11,000/250 grams', '$11.35/12 ounces', '$35.00/100 grams',
       '$21.00/16 ounces', '$29.48/8 ounces', 'HKD $140/227 grams',
       '$54.00/8 ounces', 'NT $1300/16 ounces', 'NT $2500/16 ounces',
       '$27.50/8 ounces', '$22.00/8 ounces', 'NT $580/220 grams',
       '$37.00/4 ounces'], dtype=object)

Lots of variance in how prices are recorded.  Wide arrange of currencies and units of measurements.  Some numbers are stored as the written word which makes conversion to int and regex matching difficult.

The most common units of measurements are ounces and grams.
Rare occurences (pounds)

The most common currencies are USD, NT, and HKD.
Rare occurences (yen, pound, euros, CAD)

Plan: Use regex to extract the numeric portions, currency, and the unit (ounce/gram).  See what percentage of data is captured.

In [9]:
# remove unwanted characters
Coffee_df['est_price'] = Coffee_df['est_price'].map(lambda x: str(x).replace(',',''))

In [10]:
# extract the numeric portion of the price
Coffee_df['value'] = Coffee_df['est_price'].str.extract('([0-9]*\.*[0-9]+/[0-9]*\.*[0-9]+)')
Coffee_df.value.unique()

array(['25.00/8', '59.00/8', '20.50/12', '45.00/4', '40.00/200',
       '43.00/200', '25.00/12', '20.00/6', '40.00/12', '17.95/12',
       '28.00/12', '20.00/12', '22.00/12', '23.50/12', '40.00/10',
       '24.00/12', '35.00/10', '24.00/8', '24.50/12', '23.00/12',
       '18.99/8', '22.50/12', '20.95/12', '16.95/12', '35.00/200',
       '19.25/12', '375/8', '19.00/175', '340/8', '900/4', '400/8',
       '459/8', '350/8', '19.00/12', '399/8', '249/8', '429/8',
       '21.60/12', '1500/250', '21.00/12', '22.00/6', '25.00/250',
       '25.99/10', '550/200', '380/200', '16.00/150', '45.00/12',
       '23.00/10', '26.00/12', '550/250', '16.00/12', '10.00/12',
       '13.00/12', '16.50/12', '5.00/12', '5/12', '17.00/12', '10.00/16',
       '10.00/4', nan, '500/4', '45.99/12', '18.95/12', '800/20', '460/8',
       '550/454', '550/227', '500/227', '587/8', '275/8', '840/225',
       '600/200', '1000/200', '520/200', '650/230', '700/8', '18.00/12',
       '17.50/12', '30.00/12', '1200/4', '600/50', '325/8', '200/8',
       '14.00/250', '13.00/250', '450/200', '500/200', '12.50/100',
       '30.00/250', '520/227', '8.40/4', '18.05/12', '680/230', '15.00/8',
       '21.95/12', '47.95/8', '27.00/14', '2300/230', '19.50/10',
       '30.00/4', '750/230', '450/8', '500/8', '29.00/4', '49.00/10',
       '390/8', '25.50/12', '300/4', '350/4', '240/8', '32.25/8',
       '16.95/16', '850/240', '25.00/14', '16.70/12', '39.50/12',
       '80.00/8', '17.99/12', '16.99/12', '23.00/8', '26.00/10',
       '888/225', '275/200', '165/8', '600/227', '54.95/8', '28.50/12',
       '18.50/12', '19.95/12', '12.00/12', '400/16', '650/225',
       '15.00/12', '21.50/16', '18.50/16', '8.00/4', '50.00/4', '18.00/8',
       '60.00/150', '14.00/230', '18.99/16', '1250/60', '880/200',
       '630/200', '420/200', '550/4', '19.00/6', '450/227', '18.65/12',
       '65.00/8', '15.95/12', '39.45/12', '130/350', '120/350', '1800/60',
       '50/10', '460/454', '18.99/12', '18.75/12', '19.50/12',
       '24.50/5.5', '349/8', '26.50/6', '789/8', '14.00/12', '19.50/6',
       '13.99/12', '650/8', '17.75/12', '500/100', '800/8', '18.45/12',
       '360/8', '62.95/8', '22.50/10', '27.50/12', '25.00/6', '330/113',
       '19.99/12', '498/105', '620/100', '450/220', '33.00/200',
       '22.00/16', '35.00/8', '600/8', '280/8', '200/115', '16.00/5',
       '950/227', '25.00/4', '35.00/12', '16.00/4', '350/227', '700/4',
       '400/4', '17.00/4', '140.00/4', '800/100', '700/100', '65.95/8',
       '3600/100', '19.95/7', '14.50/12', '15.00/300', '600/275',
       '17.95/16', '13.25/12', '12.99/12', '18.20/24', '9.98/12',
       '17.50/10', '400/225', '160/454', '160/227', '48.00/12', '295/115',
       '750/227', '250/200', '350/200', '69.00/6', '40.00/4', '40.95/4',
       '18.00/6', '42.00/4', '26.00/8', '20.00/4', '15.99/12', '36.00/8',
       '470/225', '370/225', '380/8', '250/8', '300/8', '49.95/8',
       '24.99/12', '350/240', '400/240', '400/227', '11.75/10.5',
       '1000/227', '800/227', '490/150', '480/400', '45.00/16',
       '35.00/16', '300/200', '34.95/8', '24.95/8', '450/240', '210/8',
       '38.50/12', '475/113', '13.95/4', '29.00/12', '650/200', '650/455',
       '350/230', '300/230', '12.25/10.5', '850/8', '30.00/8', '20.00/8',
       '800/16', '208/120', '100/150', '16.00/10', '12.00/8', '550/8',
       '50.00/6', '19.00/4', '21.99/12', '20.99/12', '75.00/12', '1250/4',
       '1400/4', '1000/4', '280.00/70', '16.00/250', '16.50/250',
       '89.95/8', '35.00/300', '575/4', '380/227', '150.00/4', '145.00/4',
       '26.50/4', '1680/100', '95.00/4', '375/4', '60.00/8', '120.00/6',
       '49.99/16', '28.00/225', '11.99/4', '88/16', '78/16', '400/120',
       '600/4', '225/8', '22.49/12', '19.49/12', '42.00/12', '24.95/12',
       '250/227', '450/115', '14.99/12', '13.95/12', '200/453', '32.00/4',
       '29.99/5', '40.00/8', '32.00/6', '760/4', '280/10', '300/225',
       '24.95/4', '21.50/8', '27.00/12', '13.01/12.64', '80.00/12',
       '260/200', '10.99/10.5', '14.95/12', '1780/250', '570/250',
       '1580/250', '600/100', '1200/225', '260/8', '650/227', '30.00/6',
       '300/100', '138/100', '21.00/113', '45.00/175', '14.95/6',
       '755/113', '320/8', '400/230', '260/227', '54.95/12', '39.95/12',
       '21.50/12', '450/225', '530/12', '13.20/12', '74.95/4', '410/8',
       '630/225', '290/8', '680/227', '118/200', '2980/100', '380/12',
       '200/160', '5.50/12', '2.00/200', '4.49/280', '4.00/12', '4.25/12',
       '16.00/8', '87.00/12', '500/150', '650/150', '1450/150', '350/250',
       '28.99/12', '17.90/12', '29.95/4', '350/16', '17.99/16',
       '1050/100', '220/8', '15.99/10', '20.49/12', '30.00/300',
       '15.80/12', '24.75/12', '900/227', '320/200', '30.00/150',
       '560/227', '32.99/16', '2200/16', '14.74/16', '500/225', '330/227',
       '10.00/8', '11.00/375', '1280/100', '600/225', '360/225',
       '350/225', '28.00/8', '49.95/7', '17.50/8', '12.99/11', '16.20/12',
       '29.95/12', '87.50/8', '120.00/16', '33.00/8', '50.00/7',
       '47.00/12', '12.50/12', '400/220', '19.75/12', '19.95/6', '9.99/4',
       '16.00/230', '270/8', '14.20/12.64', '15.75/12', '39.95/4',
       '19.95/4', '28.80/500', '27.00/8', '12.99/10', '1580/100',
       '2640/50', '14.00/225', '29.50/12', '372/227', '252/227', '50/200',
       '45/250', '22.95/12', '450/454', '16.95/6', '310/8', '620/8',
       '18.95/16', '600/230', '18.65/8', '1300/4', '25.00/150',
       '39.00/12', '599/227', '499/227', '33.00/10', '27.00/10',
       '450/460', '1500/230', '900/100', '620/4', '2420/200', '10.00/250',
       '470/227', '360/115', '50.00/10', '56.00/8', '206.00/8', '1100/8',
       '55.00/8', '1000/8', '24.00/16', '75.00/16', '65.00/16', '32.00/7',
       '350/20', '85.00/6', '330/200', '74.95/8', '39.95/8', '20/12',
       '900/8', '45/10', '5000/20', '64.95/4', '29.00/8', '31.00/8',
       '750/4', '29.99/10', '13.00/10', '32.00/8', '380/115', '550/225',
       '22.00/225', '80/200', '19.99/8', '550/230', '2500/100', '12.95/6',
       '15.00/4', '60.00/30', '500/16', '18.25/12', '22.99/12', '330/16',
       '700/230', '20.00/16', '24.99/10', '18.49/12', '16.99/14',
       '50.00/12', '550/450', '19.00/7', '23.00/6', '19.98/4', '520/250',
       '19.95/2', '475/250', '400/222', '17.00/150', '11.50/12', '3.99/8',
       '4.50/12', '18.99/50', '4.59/10.5', '200/150', '46.50/12',
       '18.00/4', '15.00/20', '300/220', '38.00/8', '13.50/12', '18.95/4',
       '30.00/10', '35.00/7', '17.80/12', '580/200', '225/4', '36.00/12',
       '45.95/8', '34.95/6', '49.95/4', '33.00/12', '15.25/12', '530/200',
       '12.36/12', '16.25/12', '18.20/12', '18.00/16', '150/250',
       '19.99/340', '12.95/16', '34.95/7', '17.88/227', '16.88/227',
       '29.95/1', '18.40/12', '10.95/12', '14.99/10', '11.29/12',
       '6.99/16', '4.99/12', '9.29/22', '8.99/32', '10.49/12', '1600/4',
       '320/227', '440/8', '19.95/8', '14.25/12', '16.00/14', '1000/100',
       '12.00/500', '120000/200', '15.00/500', '16.80/12', '8.00/100',
       '200/227', '18.00/300', '15.25/8', '570/200', '450/250', '69.95/6',
       '100/18', '60.00/100', '200/200', '280/454', '17.20/12',
       '19.20/12', '16.90/12', '1400/8', '1300/8', '125.00/4', '700/16',
       '680/225', '15.00/10', '500/230', '1200/200', '23.95/12',
       '100.00/21', '18.00/18', '13.50/8', '15.00/250', '380/454',
       '1200/16', '16.25/10', '54.95/6', '1350/230', '1200/100',
       '50.00/8', '103.95/250', '99.75/250', '600/450', '380/450',
       '17.10/12', '18.70/12', '15.45/12', '19.65/8', '34.99/16',
       '1200/230', '40.50/10', '700/227', '25.75/4', '60.00/10',
       '200/250', '18.95/8', '16.40/12', '13.34/4', '15.50/12',
       '21.20/12', '700/400', '15.90/12', '17.25/12', '12.95/12',
       '13.56/12', '9.99/12', '660/225', '125.00/250', '180/8', '49.50/4',
       '31.00/10', '29.00/10', '63.95/8', '49.00/8', '19.00/200',
       '17.99/3', '18.99/2', '37.99/6', '27.00/16', '490/16', '7.12/120',
       '37.50/8', '18.00/340', '19.00/8', '480/8', '650/16', '360/16',
       '48.95/8', '36.95/8', '28.00/500', '28.99/16', '29.00/150',
       '850/225', '28.85/8', '100/200', '250/225', '19.99/16', '44.95/8',
       '29.99/32', '250/16', '55.00/12', '24.00/6', '45.00/8', '54.00/12',
       '39.99/12', '9.00/8', '10.99/8', '300/227', '70.00/8', '1450/8',
       '15.00/200', '37.00/120', '13.50/10', '12.25/12', '2600/227',
       '6.00/250', '75.00/8', '14.45/12', '16.75/12', '11.95/12',
       '1400/16', '1500/16', '2000/16', '13.75/12', '14.75/12',
       '15.16/500', '22.15/500', '8.99/8', '9.99/7', '16.98/45', '550/16',
       '580/8', '14000/200', '4.65/8.4', '20.00/250', '600/16', '520/16',
       '1500/8', '850/16', '12.00/25.4', '3.49/11', '3.99/12', '65.99/12',
       '4.00/10', '84.00/24', '16.99/16', '19.98/16', '16.00/16',
       '15.99/16', '20.50/16', '750/16', '480/16', '17.60/12', '480/225',
       '630/227', '420/227', '450/16', '29.00/200', '320/250', '16.49/12',
       '145.00/8', '12.60/12', '13.95/8', '30.50/4', '51.00/8', '950/8',
       '9.94/4', '15.50/340', '415/12', '11000/250', '11.35/12',
       '35.00/100', '21.00/16', '29.48/8', '140/227', '54.00/8',
       '1300/16', '2500/16', '27.50/8', '22.00/8', '580/220', '37.00/4'],
      dtype=object)

In [11]:
Coffee_df.value.count()

2246

In [12]:
# extract the unit of measurement
Coffee_df['unit'] = Coffee_df['est_price'].str.extract('(ounces|grams|pounds)')
Coffee_df.unit.unique()

array(['ounces', 'grams', nan, 'pounds'], dtype=object)

In [13]:
Coffee_df['unit'].count()

2210

In [14]:
# extract the currency
Coffee_df['currency'] = Coffee_df['est_price'].str.extract('(NT|HKD|CAD|KRW|AUD|AED|IDR|€|£|¥|RM|[eE]uro)')
Coffee_df.currency.unique()

array([nan, 'NT', 'CAD', 'RM', '£', 'HKD', '¥', '€', 'IDR', 'AUD', 'AED',
       'Euro', 'KRW'], dtype=object)

In [15]:
Coffee_df.currency.count()

611

In [16]:
# If unknown currency, assume USD
Coffee_df.currency.fillna('$', inplace=True)
Coffee_df.currency.unique()

array(['$', 'NT', 'CAD', 'RM', '£', 'HKD', '¥', '€', 'IDR', 'AUD', 'AED',
       'Euro', 'KRW'], dtype=object)

In [17]:
# remove rows that could not be converted
Coffee_df = Coffee_df.dropna(subset=['currency', 'value', 'unit'])
Coffee_df.shape

(2200, 40)

In [18]:
Coffee_df[['currency', 'value', 'unit']]

     currency     value    unit
0           $   25.00/8  ounces
1           $   59.00/8  ounces
2           $  20.50/12  ounces
3           $  20.50/12  ounces
4           $   45.00/4  ounces
...       ...       ...     ...
2277        $   28.00/8  ounces
2278       NT   580/220   grams
2279        $  55.00/12  ounces
2280        $  25.00/12  ounces
2281        $   37.00/4  ounces

[2200 rows x 3 columns]

In [19]:
import sympy

#Coffee_df[['value']].apply(lambda x: sympy.sympify(x))
#Coffee_df[['value']].eval('value', target=Coffee_df)



def convert(s):
    try:
        return float(s)
    except ValueError:
        num, denom = s.split('/')
        return float(num) / float(denom)

Coffee_df['value'] = Coffee_df['value'].apply(lambda x: convert(x))
Coffee_df.astype({'value': 'float'}).dtypes
Coffee_df[['value']]

          value
0      3.125000
1      7.375000
2      1.708333
3      1.708333
4     11.250000
...         ...
2277   3.500000
2278   2.636364
2279   4.583333
2280   2.083333
2281   9.250000

[2200 rows x 1 columns]

In [20]:
Coffee_df.columns

Index(['slug', 'all_text', 'rating', 'roaster', 'name', 'region_africa_arabia',
       'region_caribbean', 'region_central_america', 'region_hawaii',
       'region_asia_pacific', 'region_south_america', 'type_espresso',
       'type_organic', 'type_fair_trade', 'type_decaffeinated',
       'type_best_value', 'type_pod_capsule', 'type_blend', 'type_estate',
       'type_peaberry', 'type_barrel_aged', 'type_aged', 'location', 'origin',
       'roast', 'est_price', 'review_date', 'agtron', 'aroma', 'acid', 'body',
       'flavor', 'aftertaste', 'desc_1', 'desc_2', 'desc_3', 'region', 'value',
       'unit', 'currency'],
      dtype='object')

# Sentiment Analysis

First clean the texts by removing numbers and special symbols.  Then analyze using VADER sentiment analysis, a lexicon-based analyzer.

Vader was pretrained using social media.  This allows it to be applied directly to the coffee reviews without needing to be trained.  Pretrained models are good for small datasets because the data does not need to be split into training and test sets.

Lexicon-based analyers remove the need for a greater context because it breaks down texts into individual tokens instead of viewing the greater context.  making them a general solution for sentiment analysis without worry of being overly fit.


https://towardsdatascience.com/the-most-favorable-pre-trained-sentiment-classifiers-in-python-9107c06442c6

In [21]:
Coffee_df['desc_1'].count

<bound method Series.count of 0       Richly floral-toned, exceptionally sweet. Dist...
1       Richly aromatic, chocolaty, fruit-toned. Dark ...
2       High-toned, fruit-driven. Boysenberry, pear, c...
3       Delicately fruit-toned. Guava, ginger blossom,...
4       Richly fruit-forward, floral-toned. Lychee, te...
                              ...
2277    Bright, crisp, deeply sweet. Honey, lilac, ced...
2278    Crisp, sweetly tart. Dark chocolate, pie cherr...
2279    Complex, uniquely sweet, tropical. Plumeria, r...
2280    High-toned, richly sweet. Strawberry guava, ro...
2281    Spice-toned, richly sweet. Raspberry, dark cho...
Name: desc_1, Length: 2200, dtype: object>

In [22]:
Coffee_df['desc_2'].count

<bound method Series.count of 0       Produced by Wilton Benitez of Macarena Farm en...
1       Produced by Rigoberto Herrera of Granja La Esp...
2       Produced at Mengesha Farm from selections of i...
3       Produced by Victor Gutiérrez of Finca Mirador ...
4       Produced by Jamison Savage of Finca Debra enti...
                              ...
2277    This coffee tied for the fourth-highest rating...
2278    This coffee tied for the third-highest rating ...
2279    This exceptional coffee was selected as the No...
2280    This exceptional coffee was selected as the No...
2281    This coffee tied for the third-highest rating ...
Name: desc_2, Length: 2200, dtype: object>

In [23]:
Coffee_df['desc_3'].count

<bound method Series.count of 0       A nuanced, complex experimentally processed Co...
1       A trifecta of fruit, chocolate and flowers, bo...
2       A fruit medley in a cup — think boysenberry an...
3       An appealing washed anaerobic cup: deep-toned,...
4       A floral- and fruit-driven anaerobic natural P...
                              ...
2277    A fine introduction to a rare variety of Arabi...
2278    An inviting natural-processed coffee from Ethi...
2279    A dynamic coffee with complex aromatics that i...
2280    A graceful, generously fruit- and floral-toned...
2281    An elegant, richly sweet natural-processed Pan...
Name: desc_3, Length: 2200, dtype: object>

In [24]:
import nltk
import re

# remove special characters
def clean(text):
    text = re.sub('[^A-Za-z]+', ' ', str(text))
    return text

# place cleaned descriptions into new columns with identifiable names
Coffee_df['blind_assessment'] = Coffee_df['desc_1'].apply(clean)
Coffee_df['notes'] = Coffee_df['desc_2'].apply(clean)
Coffee_df['bottom_line'] = Coffee_df['desc_3'].apply(clean)
Coffee_df[['blind_assessment', 'notes', 'bottom_line']].head()

,blind_assessment,notes,bottom_line
0,Richly floral toned exceptionally sweet Distin...,Produced by Wilton Benitez of Macarena Farm en...,A nuanced complex experimentally processed Col...
1,Richly aromatic chocolaty fruit toned Dark cho...,Produced by Rigoberto Herrera of Granja La Esp...,A trifecta of fruit chocolate and flowers both...
2,High toned fruit driven Boysenberry pear cocoa...,Produced at Mengesha Farm from selections of i...,A fruit medley in a cup think boysenberry and ...
3,Delicately fruit toned Guava ginger blossom co...,Produced by Victor Guti rrez of Finca Mirador ...,An appealing washed anaerobic cup deep toned n...
4,Richly fruit forward floral toned Lychee tea r...,Produced by Jamison Savage of Finca Debra enti...,A floral and fruit driven anaerobic natural Pa...

In [25]:
!pip install vaderSentiment
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: vaderSentiment in /usr/local/lib/python3.9/dist-packages (3.3.2)
Requirement already satisfied: requests in /usr/local/lib/python3.9/dist-packages (from vaderSentiment) (2.27.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests->vaderSentiment) (1.26.15)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests->vaderSentiment) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests->vaderSentiment) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.9/dist-packages (from requests->vaderSentiment) (2.0.12)

In [26]:
# https://stackoverflow.com/questions/40325980/how-is-the-vader-compound-polarity-score-calculated-in-python-nltk
# polarity_scores output into 4 classes of sentiments (neg, neu, pos, compound (aggregated score))

analyzer = SentimentIntensityAnalyzer()

def analyze_text(text):
    sentiment = analyzer.polarity_scores(str(text))
    return sentiment['compound']


Coffee_df['blind_assessment_sentiment'] = Coffee_df['blind_assessment'].apply(analyze_text)
Coffee_df['notes_sentiment'] = Coffee_df['notes'].apply(analyze_text)
Coffee_df['bottom_line_sentiment'] = Coffee_df['bottom_line'].apply(analyze_text)

Coffee_df[['blind_assessment', 'blind_assessment_sentiment']]

,blind_assessment,blind_assessment_sentiment
0,Richly floral toned exceptionally sweet Distin...,0.8832
1,Richly aromatic chocolaty fruit toned Dark cho...,0.8316
2,High toned fruit driven Boysenberry pear cocoa...,0.7184
3,Delicately fruit toned Guava ginger blossom co...,0.7430
4,Richly fruit forward floral toned Lychee tea r...,0.8176
...,...,...
2277,Bright crisp deeply sweet Honey lilac cedar te...,0.8479
2278,Crisp sweetly tart Dark chocolate pie cherry c...,0.6486
2279,Complex uniquely sweet tropical Plumeria roast...,0.9313
2280,High toned richly sweet Strawberry guava roast...,0.9061
2281,Spice toned richly sweet Raspberry dark chocol...,0.9042